### ISSUE TITLE
Provide XSLT for mapping from DataCite to RDF

### ISSUE THREAD

**Issue by nichtich** [SPAROntologies/datacite#1]
The outdated repository contains [an XSLT script to transform DataCite into RDF Turtle](https://github.com/datacite/ontology/blob/master/datacite2.2ttl.xsl). Please provide an updated version to transform DataCite to RDF/XML (Turtle is easier to read but would require additional escaping of string values).

**Comment by essepuntato** [comment]
Hi @nichtich 

The very latest version of the XSLT for transforming DataCite XML into RDF (according to SPAR Ontologies) have been created by @efgramsbergen according to the [DataCite2RDF: Mapping DataCite Metadata Schema 3.1 Terms to RDF](https://doi.org/10.6084/m9.figshare.2075356) published in 2016.

@efgramsbergen, if you are happy with this, could you please do a pull request to this repo, adding a directory "material" in the root, and then your XSLT there?

**Comment by essepuntato** [comment]
Hi @nichtich 

@efgramsbergen has just added the XSLT file to the repository. You can find it at https://github.com/SPAROntologies/datacite/blob/master/xslt/xml2rdf.xslt.

Have a nice day :-)

S.
